class DefineConstants:
    DRAGON_SOUL_STRENGTH_MAX = 7
    WORD_MAX = 0xffff
    CLIENT_VERSION = "20210328"
    LSS_SECURITY_KEY = "pouytrewqlkjhgfdsamnbvcxz0987654321"
    VERSION = "2803"
    PARTY_CAN_JOIN_MAX_LEVEL = 30
    DEFAULT_MOVE_SPEED = 200
    MAX_MEMBER_INTRO_PARTY = 8
    MAX_ITEM_STACK = 5000
    ABILITY_MAX_LEVEL = 10
    QUEST_NAME_MAX_LEN = 32
    QUEST_STATE_MAX_LEN = 64
    SAFEBOX_MAX_NUM = 135
    SAFEBOX_PASSWORD_MAX_LEN = 6